language: android
android:
  components:
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - sys-img-x86-android-23
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script: gradle test
after_success:
    - gradle cobertura coveralls
notifications:
  slack: globo:F1iVlyrzR4iX8OS7h8fwMcqx
