language: android
android:
  components:
    - build-tools-21.1.2
    - android-19
    - extra-android-m2repository
    - sys-img-x86-android-19
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script: gradle test
notifications:
  slack: globo:F1iVlyrzR4iX8OS7h8fwMcqx
